FROM fschlatt/natural-language-processing-exercises:0.0.1

# Add requirements.txt and run.py to the container
ADD run.py /code/run.py

# Define the entry point for the container
ENTRYPOINT ["python3", "/code/run.py"]